# Generated by Django 5.0.6 on 2024-05-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditioningService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=100, verbose_name='Номер')),
                ('place', models.CharField(max_length=100, verbose_name='Тип приміщення')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=100, verbose_name='Номер')),
                ('place', models.CharField(default='', max_length=100, null=True, verbose_name='Послуги')),
                ('address', models.CharField(max_length=100, verbose_name='Адреса')),
            ],
        ),
    ]
