# Generated by Django 4.2.7 on 2026-01-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.CharField(max_length=100, verbose_name='Послуга'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='place',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Послуги'),
        ),
    ]
