# Generated by Django 5.2.10 on 2026-07-12 12:02

from django.db import migrations, models


def backfill_completed_at(apps, schema_editor):
    for model_name in ("Order", "ServiceOrder"):
        model = apps.get_model("service", model_name)
        model.objects.filter(status="done", completed_at__isnull=True).update(completed_at=models.F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_order_service_reminder_12m_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_completed_at, migrations.RunPython.noop),
    ]
