# Generated by Django 4.2.7 on 2026-02-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_conditionerorder_workflow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='airconditioner',
            name='conditioner_type',
            field=models.CharField(choices=[('normal', 'Звичайний'), ('inverter', 'Інверторний')], db_index=True, default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='airconditioner',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='airconditioner',
            name='energy_class',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='airconditioner',
            name='is_in_stock',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='airconditioner',
            name='power_btu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airconditioner',
            name='recommended_area_m2',
            field=models.PositiveIntegerField(db_index=True, default=20),
        ),
        migrations.AddField(
            model_name='airconditioner',
            name='warranty_months',
            field=models.PositiveSmallIntegerField(db_index=True, default=12),
        ),
        migrations.AddField(
            model_name='conditionerorder',
            name='service_reminder_12m_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conditionerorder',
            name='service_reminder_6m_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conditionerorder',
            name='unaccepted_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
