# Generated by Django 5.2.10 on 2026-06-20 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_airconditioner_conditioner_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('source_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(db_index=True, default='catalog', max_length=120)),
                ('subcategory', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('series', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('product_type', models.CharField(choices=[('air_conditioner', 'Air conditioner'), ('air_conditioner_set', 'Air conditioner set'), ('indoor_unit', 'Indoor unit'), ('outdoor_unit', 'Outdoor unit'), ('panel', 'Panel'), ('accessory', 'Accessory'), ('ventilation', 'Ventilation'), ('heat_pump', 'Heat pump'), ('multi_split', 'Multi split'), ('semi_industrial', 'Semi-industrial'), ('other', 'Other')], db_index=True, default='air_conditioner', max_length=50)),
                ('short_description', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='catalog/products/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_indexable', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_products', to='catalog.company')),
            ],
            options={
                'ordering': ('brand__name', 'model'),
            },
        ),
        migrations.CreateModel(
            name='CatalogProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('panel', 'Panel'), ('remote', 'Remote'), ('option', 'Option')], max_length=30)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_sets', to='catalog.catalogproduct')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.catalogproduct')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/products/')),
                ('source_sheet', models.CharField(blank=True, default='', max_length=100)),
                ('anchor_row', models.PositiveIntegerField(blank=True, null=True)),
                ('anchor_col', models.PositiveIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.catalogproduct')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogProductImportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=255)),
                ('source_sheet', models.CharField(max_length=100)),
                ('source_row', models.PositiveIntegerField()),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_row_json', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sources', to='catalog.catalogproduct')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('block', 'Block'), ('set', 'Set'), ('wholesale', 'Wholesale'), ('retail', 'Retail'), ('dealer', 'Dealer'), ('gross', 'Gross')], max_length=30)),
                ('currency', models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_sheet', models.CharField(blank=True, default='', max_length=100)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.catalogproduct')),
            ],
            options={
                'ordering': ('product', 'price_type', 'currency'),
            },
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['brand', 'model'], name='catalog_cat_brand_i_84e185_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['category', 'series'], name='catalog_cat_categor_16d20b_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogproductcomponent',
            constraint=models.UniqueConstraint(fields=('parent_product', 'component_product', 'role'), name='uniq_catalog_product_component_role'),
        ),
        migrations.AddConstraint(
            model_name='catalogproductimage',
            constraint=models.UniqueConstraint(fields=('product', 'source_sheet', 'anchor_row', 'anchor_col'), name='uniq_catalog_product_image_anchor'),
        ),
        migrations.AddIndex(
            model_name='catalogproductimportsource',
            index=models.Index(fields=['source_sheet', 'source_row'], name='catalog_cat_source__813fc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogproductimportsource',
            constraint=models.UniqueConstraint(fields=('source_file', 'source_sheet', 'source_row'), name='uniq_catalog_product_import_source'),
        ),
        migrations.AddIndex(
            model_name='catalogproductprice',
            index=models.Index(fields=['price_type', 'currency'], name='catalog_cat_price_t_95e1fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogproductprice',
            constraint=models.UniqueConstraint(fields=('product', 'price_type', 'currency', 'source_sheet', 'source_row'), name='uniq_catalog_product_price_source'),
        ),
    ]
