# Generated by Django 5.2.10 on 2026-06-21 19:54

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def _unique_slug(CatalogProduct, base, product_id=None):
    base_slug = slugify(base)[:220] or f"product-{product_id or 'legacy'}"
    slug = base_slug
    counter = 2
    while CatalogProduct.objects.filter(slug=slug).exists():
        slug = f"{base_slug[:220]}-{counter}"
        counter += 1
    return slug


def copy_air_conditioners_to_catalog_products(apps, schema_editor):
    AirConditioner = apps.get_model("catalog", "AirConditioner")
    CatalogProduct = apps.get_model("catalog", "CatalogProduct")
    CatalogProductPrice = apps.get_model("catalog", "CatalogProductPrice")
    CatalogProductImage = apps.get_model("catalog", "CatalogProductImage")
    Color = apps.get_model("catalog", "Color")
    ConditionerOrder = apps.get_model("catalog", "ConditionerOrder")
    Review = apps.get_model("catalog", "Review")

    color_names_by_hash = {
        "#ffffff": "Білий",
        "#fff": "Білий",
        "#111111": "Чорний",
        "#000000": "Чорний",
        "#000": "Чорний",
        "#c0c0c0": "Сріблястий",
        "#808080": "Сірий",
        "#d4af37": "Золотий",
    }
    for color in Color.objects.all():
        color_hash = (color.hash or "").strip().lower()
        new_name = color_names_by_hash.get(color_hash)
        if new_name and color.name != new_name:
            color.name = new_name
            color.save(update_fields=["name"])

    type_labels = {
        "normal": "Звичайний",
        "inverter": "Інверторний",
    }

    remap = {}
    for old in AirConditioner.objects.select_related("company").prefetch_related("colors").order_by("id"):
        product = (
            CatalogProduct.objects.filter(brand_id=old.company_id, model=old.name).first()
            or CatalogProduct.objects.filter(brand_id=old.company_id, name=old.name).first()
        )
        specs = dict(getattr(product, "specs", None) or {}) if product else {}
        specs.update(
            {
                "legacy_airconditioner_id": old.id,
                "legacy_conditioner_type": type_labels.get(old.conditioner_type, old.conditioner_type),
            }
        )

        photo_name = old.photo.name if old.photo else ""
        if product is None:
            product = CatalogProduct.objects.create(
                brand_id=old.company_id,
                name=old.name,
                model=old.name,
                slug=_unique_slug(CatalogProduct, old.name, old.id),
                source_key=f"legacy-airconditioner-{old.id}",
                category="air_conditioners",
                product_type="air_conditioner",
                short_description=(old.description or "")[:300],
                description=old.description or "",
                specs=specs,
                main_image=photo_name,
                recommended_area_m2=old.recommended_area_m2,
                power_btu=old.power_btu,
                energy_class=old.energy_class or "",
                country=old.country or "",
                is_in_stock=old.is_in_stock,
                warranty_months=old.warranty_months or 24,
            )
        else:
            update_fields = []
            if not product.description and old.description:
                product.description = old.description
                update_fields.append("description")
            if not product.short_description and old.description:
                product.short_description = old.description[:300]
                update_fields.append("short_description")
            if not product.main_image and photo_name:
                product.main_image = photo_name
                update_fields.append("main_image")
            if not product.recommended_area_m2 and old.recommended_area_m2:
                product.recommended_area_m2 = old.recommended_area_m2
                update_fields.append("recommended_area_m2")
            if not product.power_btu and old.power_btu:
                product.power_btu = old.power_btu
                update_fields.append("power_btu")
            if not product.energy_class and old.energy_class:
                product.energy_class = old.energy_class
                update_fields.append("energy_class")
            if not product.country and old.country:
                product.country = old.country
                update_fields.append("country")
            if product.warranty_months in (None, 0, 24) and old.warranty_months:
                product.warranty_months = old.warranty_months
                update_fields.append("warranty_months")
            product.is_in_stock = old.is_in_stock
            update_fields.append("is_in_stock")
            product.specs = specs
            update_fields.append("specs")
            product.save(update_fields=sorted(set(update_fields)))

        for color in old.colors.all():
            product.colors.add(color)

        existing_same_price = product.prices.filter(
            price_type="retail",
            currency="UAH",
            amount=old.price,
        ).exists()
        if not existing_same_price:
            CatalogProductPrice.objects.update_or_create(
                product=product,
                price_type="retail",
                currency="UAH",
                source_sheet="legacy_airconditioner",
                source_row=old.id,
                defaults={"amount": old.price, "is_current": True},
            )

        if photo_name:
            existing_same_image = product.main_image.name == photo_name or product.images.filter(image=photo_name).exists()
            if not existing_same_image:
                CatalogProductImage.objects.update_or_create(
                    product=product,
                    source_sheet="legacy_airconditioner",
                    anchor_row=old.id,
                    anchor_col=1,
                    defaults={"image": photo_name, "is_primary": not product.images.filter(is_primary=True).exists()},
                )

        remap[old.id] = product.id

    with schema_editor.connection.constraint_checks_disabled():
        for old_id, new_id in remap.items():
            ConditionerOrder.objects.filter(conditioner_id=old_id).update(conditioner_id=new_id)
            Review.objects.filter(conditioner_id=old_id).update(conditioner_id=new_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_catalogproduct_catalogproductcomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='catalog_products', to='catalog.color'),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='energy_class',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='is_in_stock',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='power_btu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='recommended_area_m2',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='warranty_months',
            field=models.PositiveSmallIntegerField(db_index=True, default=24),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='product_type',
            field=models.CharField(choices=[('air_conditioner', 'Кондиціонер'), ('air_conditioner_set', 'Комплект кондиціонера'), ('indoor_unit', 'Внутрішній блок'), ('outdoor_unit', 'Зовнішній блок'), ('panel', 'Панель'), ('accessory', 'Аксесуар'), ('ventilation', 'Вентиляція'), ('heat_pump', 'Тепловий насос'), ('multi_split', 'Мульти-спліт'), ('semi_industrial', 'Напівпромисловий'), ('other', 'Інше')], db_index=True, default='air_conditioner', max_length=50),
        ),
        migrations.AlterField(
            model_name='conditionerorder',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.color'),
        ),
        migrations.RunPython(copy_air_conditioners_to_catalog_products, noop_reverse),
        migrations.AlterField(
            model_name='conditionerorder',
            name='conditioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.catalogproduct'),
        ),
        migrations.AlterField(
            model_name='review',
            name='conditioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogproduct'),
        ),
        migrations.DeleteModel(
            name='AirConditioner',
        ),
    ]
