# Generated by Django 5.2.10 on 2026-06-21 21:16

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models
from django.db.models import Avg, Count


def backfill_product_ratings(apps, schema_editor):
    CatalogProduct = apps.get_model("catalog", "CatalogProduct")
    Review = apps.get_model("catalog", "Review")

    ratings = (
        Review.objects
        .filter(rating__isnull=False)
        .values("conditioner_id")
        .annotate(avg=Avg("rating"), count=Count("id"))
    )
    for rating in ratings:
        rating_avg = Decimal(str(rating["avg"])).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        CatalogProduct.objects.filter(id=rating["conditioner_id"]).update(
            rating_avg=rating_avg,
            rating_count=rating["count"],
        )


def reset_product_ratings(apps, schema_editor):
    CatalogProduct = apps.get_model("catalog", "CatalogProduct")
    CatalogProduct.objects.update(rating_avg=None, rating_count=0)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_fill_catalog_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='rating_avg',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='rating_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_product_ratings, reset_product_ratings),
    ]
