# Generated by Django 5.2.10 on 2026-07-12 12:02

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_catalog_order_completed_at(apps, schema_editor):
    ConditionerOrder = apps.get_model("catalog", "ConditionerOrder")
    ConditionerOrder.objects.filter(status="done", completed_at__isnull=True).update(completed_at=models.F("updated_at"))


def supersede_duplicate_reviews(apps, schema_editor):
    Review = apps.get_model("catalog", "Review")
    duplicates = (
        Review.objects.values("conditioner_id", "user_id")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )
    for duplicate in duplicates:
        ids = list(
            Review.objects.filter(
                conditioner_id=duplicate["conditioner_id"],
                user_id=duplicate["user_id"],
            )
            .order_by("-id")
            .values_list("id", flat=True)
        )
        Review.objects.filter(id__in=ids[1:]).update(is_superseded=True)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_catalogproduct_rating_avg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionerorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_superseded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(backfill_catalog_order_completed_at, migrations.RunPython.noop),
        migrations.RunPython(supersede_duplicate_reviews, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_and_5'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('is_superseded', False)), fields=('conditioner', 'user'), name='uniq_active_review_per_user_product'),
        ),
    ]
